### ISSUE TITLE
Gem5 SE mode , ruby memory model, DerivO3CPU

### ISSUE THREAD

**Issue by arunkp1986** [cirosantilli-work/issues#6]
I am trying to run gem5 in SE mode with number of cpus 2, cpu type DerivO3CPU, and ruby memory model using following command, but the simulation does not stop even after results are produced , ie "Hello world!" is printed to stdout

build/X86_MESI_Three_Level/gem5.opt configs/example/se.py -n 2 --ruby --cpu-type=DerivO3CPU -c 'tests/test-progs/hello/bin/x86/linux/hello;tests/test-progs/hello/bin/x86/linux/hello' 

I started using ruby memory model after reading from gem5 email archive that classic memory does not work with multicore DerivO3CPU.

**Comment by cirosantilli2** [comment]
I just found out I wasn't subscribed to this repo, what a fail. Closing in favor of discussion at: https://www.mail-archive.com/gem5-users@gem5.org/msg17388.html
