### ISSUE TITLE
Gem5 16+ core simulation

### ISSUE THREAD

**Issue by theverytak** [cirosantilli-work/issues#7]
Hi, I already have been your kind solutions on stackoverflow, gem5 email thread and various github issue pages.
But lack of my intelligence, I can't still run Gem5 with more than 16 cores.
I left a [comment](https://github.com/cirosantilli2/gem5-issues/issues/13) on the closed issue. Would you be kind enough to look at it?

Thank you for your help in advance.

**Comment by cirosantilli2** [comment]
It is never the user's fault, it's always either a bug or lack of documentation. Closing this, let's move all talk over there.
